FROM opensuse/portus:head

COPY portus.yml /srv/Portus/config/config.yml
ADD https://raw.githubusercontent.com/SUSE/Portus/master/examples/development/vagrant/conf/ca_bundle/server.key /certificates/portus.key
